apiVersion: apps/v1
kind: Deployment
metadata:
  name: cursos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cursos
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cursos
    spec:
      containers:
      - image: grangux/cursos:v2
        name: cursos
        ports:
        - containerPort: 8001
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"