apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - image: grangux/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
