apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: mysql:8.0.31
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_USER
          value: user
        - name: MYSQL_ROOT_PASSWORD
          value: password
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc