apiVersion: apps/v1
kind: Deployment
metadata:
  name: cursos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cursos
  template:
    metadata:
      labels:
        app: cursos
    spec:
      containers:
      - image: grangux/cursos:latest
        name: cursos
        ports:
        - containerPort: 8001
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: cursos
                key: profile
          - name: DATA_BASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cursos
                key: password