apiVersion: v1
kind: Secret
metadata:
  name: usuarios
type: Opaque
data:
  username: dXNlcg==
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: cursos
type: Opaque
data:
  username: dXNlcg==
  password: cGFzc3dvcmQ=