apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: postgres14
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres14
  type: ClusterIP
status:
  loadBalancer: {}
